server:
  port: 8093
  servlet:
    context-path: /api

spring:
  datasource:
    name: log_and_proof_back
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/aaa?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


  mapper-locations:
    classpath:mappers/*.xml
  type-aliases-package:
    com/example/log_and_proof_back/model/entity

mybatis:
  mapper-locations:
    classpath:mappers/*.xml
  type-aliases-package:
    com/example/log_and_proof_back/model/entity
