server:
  port: 8095


spring:
  datasource:
    name: log_and_proof_back
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chen1213
    url: jdbc:mysql://localhost:3306/yh_oa?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true


